version: '3'
services:
  web:
    build: ./web
    container_name: web
    restart: always
    links:
      - postgres:postgres
    volumes:
      - web-data:/usr/src/app/static
    env_file: 
      - .env

  nginx:
    image: webapp-nginx
    build: ./nginx
    ports:
      - 5000:80
    depends_on:
      - web

  postgres:
    restart: always
    build: ./postgres
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file: 
      - .env

volumes:
  web-data: